# for GHC-8.0.1
extra-deps: [ data-stringmap-1.0.1.1, json-builder-0.3 ]
resolver: nightly-2016-06-21

# for GHC-7.10.3
# extra-deps: [ data-stringmap-1.0.1.1 ]
# resolver: lts-6.4

# for GHC-7.10.2
# extra-deps: [ data-stringmap-1.0.1.1 ]
# resolver: lts-3.22

# for GHC-7.8.4
# extra-deps: [ data-stringmap-1.0.1.1, json-builder-0.3 ]
# resolver: lts-2.22

flags: {}
packages:
- '.'
